---
- hosts: all
  tasks:
  - name: i want to install apache2 webserver
    apt:
      name: "{{webpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to install webserver on redhat
    yum:
      name: "{{webpackonredhat}}"
      state: present
    when: ansible_os_family=="Redhat"